services:
  backend:
    build: ./backend/Dockerfile
    container_name: backend
    ports:
      - "80:80"

  frontend:
    build: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"