services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: backend
    ports:
      - "80:80"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}

    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
